import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import {
  BackgroundMusic,
  FeedBackDialog,
  Footer,
  Header,
  ScrollUpButton,
} from "@/components/layout";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Safe Space",
  description: "Generated by create next app",
  icons: {
    icon: "/owl.svg",
    shortcut: "/owl.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.style} ${ubuntu.className} antialiased`}>
        <BackgroundMusic audioSrc="/music/fullmetal.mp3" volume={0.6} />
        <Header />
        <div className="xl:py-16 py-10 md:px-12 px-4 xl:px-52 xl:my-12 ">
          <div className="h-full">{children}</div>
        </div>
        <Footer />
        <ScrollUpButton />
        <FeedBackDialog />
      </body>
    </html>
  );
}
