import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/navigation/footer";
import { Header } from "@/components/navigation/header";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.style} ${ubuntu.className} antialiased`}>
        <Header />
        <div className="h-screen">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
