import type { Metadata } from "next";
import { Geist, Lobster } from "next/font/google";
import "./globals.css";

import { Bokor } from "next/font/google";

const bokor = Bokor({
  subsets: ["latin"],
  weight: "400",
});

const lobster = Lobster({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lobster.style} ${lobster.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
